[package]
name = "rumble"
version = "0.0.0"
authors = ["timokoesters", "Alexander Dmitriev", "Frederick Gnodtke <frederick@gnodtke.net>"]
edition = "2018"

[dependencies]
openssl = "0.10.16"
protobuf = "2.2.2"
byteorder = "1.2.7"

[build-dependencies]
protoc-rust = "2.2.2"
